version: 0.9.4-{build}
image: Previous Visual Studio 2019
clone_folder: c:\gopath\src\github.com\mackerelio\go-check-plugins
environment:
  GOPATH: c:\gopath
  GOROOT: c:\go114
install:
  - set PATH=%GOROOT%\bin;%GOPATH%\bin;%PATH%;C:\MinGW\bin
  - echo %Path%
  - go version
  - go env
build_script:
- go get -d -v -t ./...
- go build -o check-log/check-log.exe ./check-log
- go build -o check-procs/check-procs.exe ./check-procs
- go build -o check-windows-eventlog/check-windows-evenglog.exe ./check-windows-eventlog
test_script:
- go vet -all ./check-log/... ./check-procs/... ./check-ntservice/... ./check-windows-eventlog/...
- go test ./check-log/... ./check-procs/... ./check-ntservice/... ./check-windows-eventlog/...
